---
- name: enable surey repo
  include_tasks: repo.yml
  when: >
    ansible_distribution == 'Debian'
    and php7_version is version(php7_distro_version, "!=")

- name: create temporary list to add phpxx- to the package names
  set_fact:
    temp_list: "{% for item in php7_default_pkgs %}php{{ php7_version }}-{{ item }} {% endfor %}"

- name: split in items
  set_fact:
    package_list: "{{ temp_list.split() }}"

- name: install default required php packages | {{ php7_version }}
  apt:
    name: "{{ package_list }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: install php <=7.1 only packages
  apt:
    name:
      - php{{ php7_version }}-mcrypt
    state: present
    cache_valid_time: 3600
    update_cache: yes
  when: php7_version is version ("7.1", '<=')

- name: install php <=7.2 only packages
  apt:
    name:
      - php-uploadprogress
    state: present
    cache_valid_time: 3600
    update_cache: yes
  when: >
     php7_version is version ("7.2", '<=')
     and ansible_distribution_release != 'xenial'

- name: install packages with non standard names
  apt:
    name:
      - php-pear
      - php-imagick
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: install extra required packages
  apt:
    name: "{{ php7_extra_pkg }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes

- name: put php.ini | {{ php7_version }}
  template:
    src: php.ini.j2
    dest: "/etc/php/{{ php7_version }}/fpm/php.ini"
    owner: root
    group: root
    mode: "0644"
  notify: reload php{{ php7_version }}

- name: put php-fpm.conf | {{ php7_version }}
  template:
    src: php-fpm.conf.j2
    dest: "/etc/php/{{ php7_version }}/fpm/php-fpm.conf"
    owner: root
    group: root
    mode: "0644"
  notify: reload php{{ php7_version }}

- name: put www-data pool config-file | {{ php7_version }}
  template:
    src: www.conf.j2
    dest: "/etc/php/{{ php7_version }}/fpm/pool.d/www.conf"
    owner: root
    group: root
    mode: "0644"
  notify: restart php{{ php7_version }}

- name: make sure libapache2-mod-php{{ php7_version }} is not present, use fpm!
  apt:
    name:
      - "libapache2-mod-php{{ php7_version }}"
      - libapache2-mod-php
    state: absent
  notify: restart apache2

- name: ensure service is running
  service:
    name: php{{ php7_version }}-fpm
    state: started
    enabled: true
