---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart php7.0
  service:
    name: php7.0-fpm
    state: restarted
    enabled: true

- name: reload php7.0
  service:
    name: php7.0-fpm
    state: reloaded
    enabled: true

- name: restart php7.1
  service:
    name: php7.1-fpm
    state: restarted
    enabled: true

- name: reload php7.1
  service:
    name: php7.1-fpm
    state: reloaded
    enabled: true

- name: restart php7.2
  service:
    name: php7.2-fpm
    state: restarted
    enabled: true

- name: reload php7.2
  service:
    name: php7.2-fpm
    state: reloaded
    enabled: true

- name: restart php7.3
  service:
    name: php7.3-fpm
    state: restarted
    enabled: true

- name: reload php7.3
  service:
    name: php7.3-fpm
    state: reloaded
    enabled: true

- name: restart php7.4
  service:
    name: php7.4-fpm
    state: restarted
    enabled: true

- name: reload php7.4
  service:
    name: php7.4-fpm
    state: reloaded
    enabled: true

- name: restart apache2
  service:
    name: apache2
    state: restarted
