---
name: Molecule tests

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd molecule
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      - name: Test with molecule
        run: |
          pwd
          ls
          cd molecule
          ls
          molecule --debug test --scenario-name default
          molecule --debug test --scenario-name ubuntu
        env:
          ANSIBLE_FORCE_COLOR: '1'
